FROM alpine:3.20.1 as downloader

ARG RABBITMQ_URL
ARG RABBITMQ_EXCHANGE

ADD https://github.com/Bankole2000/lerna-backend-microservices/raw/main/services/pocketbase/custompb /custompb

FROM scratch

COPY --from=downloader /custompb /custompb

EXPOSE 8090

CMD ["/custompb", "serve", '--http=0.0.0.0:8090']