FROM alpine:latest

ARG RABBITMQ_URL
ARG RABBITMQ_EXCHANGE

RUN apk add --no-cache \
    unzip \
    ca-certificates

ADD https://github.com/Bankole2000/lerna-backend-microservices/raw/main/services/pocketbase/pb.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/
# FROM scratch

# COPY --from=downloader /custompb /custompb

EXPOSE 8090

CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090"]