export const events = {
  USER_SIGNED_UP_VIA_EMAIL: 'USER_SIGNED_UP_VIA_EMAIL',
  USER_SIGNED_UP_VIA_PHONE: 'USER_SIGNED_UP_VIA_PHONE',
  USER_PHONE_VERIFIED: 'USER_PHONE_VERIFIED',
  USER_EMAIL_VERIFIED: 'USER_EMAIL_VERIFIED',
  USER_PASSWORD_RESET_REQUESTED: 'USER_PASSWORD_RESET_REQUESTED',
  USER_PASSWORD_RESET_COMPLETED: 'USER_PASSWORD_RESET_COMPLETED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  USER_CHANGED_PASSWORD: 'USER_CHANGED_PASSWORD',
  FAILED_LOGIN_ATTEMPT: 'FAILED_LOGIN_ATTEMPT',
  USER_DISABLED_ACCOUNT: 'USER_DISABLED_ACCOUNT',
  USER_DELETED_ACCOUNT: 'USER_DELETED_ACCOUNT',
};
